sudo: required
dist: xenial
language: scala
before_install:
- curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash
  && . ~/.jabba/jabba.sh
install:
- $JABBA_HOME/bin/jabba install $TRAVIS_JDK && export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK"
  && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.jabba/jdk"
before_script:
- unset _JAVA_OPTIONS
jobs:
  include:
  - stage: test
    script:
    - sbt -J-XX:ReservedCodeCacheSize=128m test
  - stage: int-test
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - curl -L https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz | tar xvz --strip 1 && chmod +x oc && sudo cp oc /usr/local/bin/ && rm oc
    - oc login https://centralpark.lightbend.com --username=$OC_USERNAME --password=$OC_PASSWORD
    - oc status
    - oc project akka-kubernetes-tests
    - export VERSION=`sbt -Dsbt.log.noformat=true cluster-sharding/docker:publish cluster-sharding/version | tail -n 1 | awk '{ print $NF }'`; echo $VERSION; cat ./cluster-sharding/kubernetes/akka-cluster.yml | sed s/latest/$VERSION/g | oc apply -f -
    - sbt -Dakka.k8s.deployment-version=$VERSION -Dakka.k8s.cluster-size=3 -Dakka.k8s.target="http://akka-kubernetes-tests.centralpark.lightbend.com" cluster-sharding/it:test
    - oc get pods
stages:
- name: test
  if: NOT tag =~ ^v
- name: int-test
  if: repo = akka/akka-kubernetes-tests
env:
  global:
  - TRAVIS_JDK=1.8.192
  - JABBA_HOME=/home/travis/.jabba
  # DOCKER_USERNAME
  - secure: cSrSMOzMvcaDUp686CcP4tG2qPMlGeaVcsBzjN3ERRF8bzC0IWGNGE4xQ6bksF15EwWMOWhn/dlEpA5segPiFuWAV5CCrXNoHlVRJo2VmOrhMVsv8WaA786VLfqabe2dAL5x+ihZLLEBW2R+WGxlEX+RtRDl3iXvpfDbMCUqLSfLi9BLLyvhAQTFYjQLPc36g/rINXWbnCZOyaWtEfSE99zeYxQuAUg+621unnJukSTEkQMMG4+3AHu4ZwMk/Zit7TDkoi02UPCYZ85fr1uszLMpXt9sDc+b4loisUfws2eoHNL6z9R+jEahU412g1Fxn7R/7gG3u5at7cqfFHzerM2/mDLAcwQUdY76lqzZqT7MjI/4Ssy086qYv45ChkasmU/Lxbfk4NhlgbFUdcwRYikghj7oYrsZHvEm/fRZYHmzTRzrH4RWNFBetGaFiycS8F8paabTcee/euIZ8wHXafTRdl7MsG1nQRJ9Oa6egmgv8YzrmyQvTJqAiLt6ZA5NhFWs8IdqHt6Co1l3n7QmpExtkYOhm98UTuHY2lsA05dIOaE83w0TNYmYaqqK0D+LiLhJHX+8s2rVh79kSblz1fbmVqXlb0t2sljffxMbVcHtTTA5AzZhamMAZv35rg8/RvQqYaf5TXFMktzaAw7odoAwYgTun/nYQIU83oFX8LU=
  # DOCKER_PASSWORD
  - secure: 0Ln/anHivt4fBpE5RI3zKI8oPdH7h9b65iXsf6Ao6vcM+htzo0plUS8lQmU9RedbtpgD7mNb6nGxFNHDrWjzgRJnueb7+Bzp7AmhXAr6tw4hn+8KO2JyEDK8EIOgbPTyqi42y1yK4mjZwUuOhlNzlObRbenDREHLBx8XJpHiDqq7Sh5j84pWSVYpxB1qe/ug5RwZ1ABIOcXhjzsmYYVVKnGO2UJ3lL1ClRJKoJKADNcqkUq77j38RCHq8X4nWsmmh7uk8mt8U0nPcECTfrdlFvrXzg/FM46FYTJ1329igaF1zVGlaNbzL5UKxhZHuXGXC74I+gD9vk7Y8Tvc1o6bhOl+VHZNLZl6pZSU5b5MRFXhuHTHS/9SYiiPburQOuuT41dT2tdue07+XFK/FzKED+GTek/XptZbXmabAXVFQeNxU+5BWPQltKLMFNv5r839ac5ScJu8zhS2OomR9S+2RGn3jViWWQLCXzdvFdogEueNmGmWiRaxHD1TzqsaLBkHK+4G/1C0dKia2X0FrXwqIKHyssX5J65nFKKIVmhCJgHE2GiWJvnGWLqVyaXnAdOafP0ftKOODBAc8geroIGIbHTmQSsMBN0rKuJ5euACFcneU2Z9PIujXBUqYRQYleVOia2RLhGoqUEtC1DvQJDa2hZ1SIHH9FwT9jqX0dygy8A=
  # OC_USERNAME
  - secure: 12TYOcKE5ebabl0e8ZcTGmki5+gpQGvbcmab2XudjaiE9UN4nqceinfbZ2Z2RoDRzg1rlc6beGNl6cuv1s1m/2ZlIrK59kFopKw5qJSBxzr7RadY90ChVK5Fl5ftdfjwsliHYd+ngsLld7BXUZyZkMw5z9cYmOPRqzHZWtFenffQ3uqVsKojwdk0HsLZ8/n284Ixhw6qxLoylcJvEGimpSKghzYWKlS58I2ivjLEtmLw8y+M+IfPYWcz9Vmttk3m3pEGOQy5TRFHIf7WQ2B1N5hQ9hP3vE2QUHrnR2S9BzENs92T1GXdZn14XbxmzUfdAzRmIX95EGkaMpJfST5XKh2D8URB8rAtn9bhO5IlygeJv6lKm8NJbp9Zl6SB/9utLNekRbJnWJiQQbW+GqzewZ32LP13qObvnnfIFexzJFMuTMEKlOektX/w2YNN1JVwidADl+s3dLgCdtZwnIpEcKpTMY9+amgHqnpmH9vY86/AHaeY1EwDV+xUBGFkWiXtgmcYTaGcdVXFCFrmEyDlLEDfHPI7h2MkGaWFDOldHqj4NhUmvu90ABaG2W1M1oWoElVpvSSLfuajMzQNKOliXW+FEgBeFp04pJX1lvgUpK7Fw2oM/Z5C7kLLRdQk18TstQCwUD0Msj6pYz5B/MVyDXMRgGPaH+AKjwotMmCCqMs=
  # OC_PASSWORD
  - secure: rncX3iNc/SRvazwju1UAwMPpFdMBpUe+TkdsdteGCZkdqYGca00t7eLU1OaFnWpfrrW/dNIME9HzTb4bIVc44QnWpYAoXVUZUuUZBfDtp0LKyjoviHzPFbvxMicchjHWDZaLEVsKO42mTLyB8rmF0iRd59dqoZZVO1myXpzpLPPSTsKGX+uvo0ANZD86aGP/SvaJJXlGVhKT5uFGETPxZ8YcwVu4IaRSipQ7UHDCSr+tqlXoe7BUcK3DVpiW1AhCiynt2Kz5QTV2tol4WH2nG18DNZxIy6vPUu/+bkbMHOHLFX1lJzWhEQamk3DC57APBdqHtg+v78p1ow4sDklU+MsORyy3zeFL5ailL4WdrwXU9STutYqD1XBn7FvJ5ZpRAU4zLeYvNrQDhcbogd+S5DSIN+aFEt8pDk6QxI9TUZX0GgZPxAe86VEilRaWsP4FYtMPAoZ1q/P4PI2ABwEJOVOIqEr01UDWkKGOWgMrpsZ4K5+MrFtqaQ15PcsxBSiVMoZGFRk28OAfPvyrhY5hOpZyylkfmGZLBNnj2k02KTviCKjL354s709Z78a2UKwkFCEphrSo+IfjUcgn92gjk0czWQmBjvTbSEZ6Z/x3H/ErQqR0DX9segStqeM60cKrjAEEH0LDq+LEACENRmP1pa2cHMfHv3QD2chca4iUf8w=
services:
- docker
