sudo: required
dist: xenial
language: scala

jdk:
  - oraclejdk8

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - $JABBA_HOME/bin/jabba install $TRAVIS_JDK && export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba/jdk

before_script:
  - unset _JAVA_OPTIONS

jobs:
  include:
  - stage: test
    script:
    - sbt -J-XX:ReservedCodeCacheSize=128m test
    env: TEST
  - script: sbt -Dakka.k8s.cluster-size=3 -Dakka.k8s.target="http://akka-kubernetes.centralpark.lightbend.com"   it:test
    env: INT_TEST

stages:
  - name: check
    if: NOT tag =~ ^v
  - name: test
    if: NOT tag =~ ^v

env:
  global:
    - TRAVIS_JDK=1.8.192
    - JABBA_HOME=/home/travis/.jabba
