sudo: required
dist: xenial
language: scala
jdk:
- oraclejdk8
before_install:
- curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash
  && . ~/.jabba/jabba.sh
install:
- $JABBA_HOME/bin/jabba install $TRAVIS_JDK && export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK"
  && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.jabba/jdk"
before_script:
- unset _JAVA_OPTIONS
jobs:
  include:
  - stage: test
    script:
    - sbt -J-XX:ReservedCodeCacheSize=128m test
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - curl -L https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz | tar xvz --strip 1 && chmod +x oc && sudo cp oc /usr/local/bin/ && rm oc
    - oc login https://centralpark.lightbend.com --token=$OC_TOKEN
    - oc status
    - oc project akka-kubernetes
    - version=`sbt -Dsbt.log.noformat=true docker:publish version | tail -n 1 | awk '{ print $NF }'`; echo $version; cat ./kubernetes/akka-cluster.yml | sed s/latest/$version/g | oc apply -f -
    - sbt -Dakka.k8s.cluster-size=3 -Dakka.k8s.target="http://akka-kubernetes.centralpark.lightbend.com" it:test
stages:
- name: check
  if: NOT tag =~ ^v
- name: test
  if: NOT tag =~ ^v
env:
  global:
  - TRAVIS_JDK=1.8.192
  - JABBA_HOME=/home/travis/.jabba
  # DOCKER_USERNAME
  - secure: cSrSMOzMvcaDUp686CcP4tG2qPMlGeaVcsBzjN3ERRF8bzC0IWGNGE4xQ6bksF15EwWMOWhn/dlEpA5segPiFuWAV5CCrXNoHlVRJo2VmOrhMVsv8WaA786VLfqabe2dAL5x+ihZLLEBW2R+WGxlEX+RtRDl3iXvpfDbMCUqLSfLi9BLLyvhAQTFYjQLPc36g/rINXWbnCZOyaWtEfSE99zeYxQuAUg+621unnJukSTEkQMMG4+3AHu4ZwMk/Zit7TDkoi02UPCYZ85fr1uszLMpXt9sDc+b4loisUfws2eoHNL6z9R+jEahU412g1Fxn7R/7gG3u5at7cqfFHzerM2/mDLAcwQUdY76lqzZqT7MjI/4Ssy086qYv45ChkasmU/Lxbfk4NhlgbFUdcwRYikghj7oYrsZHvEm/fRZYHmzTRzrH4RWNFBetGaFiycS8F8paabTcee/euIZ8wHXafTRdl7MsG1nQRJ9Oa6egmgv8YzrmyQvTJqAiLt6ZA5NhFWs8IdqHt6Co1l3n7QmpExtkYOhm98UTuHY2lsA05dIOaE83w0TNYmYaqqK0D+LiLhJHX+8s2rVh79kSblz1fbmVqXlb0t2sljffxMbVcHtTTA5AzZhamMAZv35rg8/RvQqYaf5TXFMktzaAw7odoAwYgTun/nYQIU83oFX8LU=
  # DOCKER_PASSWORD
  - secure: 0Ln/anHivt4fBpE5RI3zKI8oPdH7h9b65iXsf6Ao6vcM+htzo0plUS8lQmU9RedbtpgD7mNb6nGxFNHDrWjzgRJnueb7+Bzp7AmhXAr6tw4hn+8KO2JyEDK8EIOgbPTyqi42y1yK4mjZwUuOhlNzlObRbenDREHLBx8XJpHiDqq7Sh5j84pWSVYpxB1qe/ug5RwZ1ABIOcXhjzsmYYVVKnGO2UJ3lL1ClRJKoJKADNcqkUq77j38RCHq8X4nWsmmh7uk8mt8U0nPcECTfrdlFvrXzg/FM46FYTJ1329igaF1zVGlaNbzL5UKxhZHuXGXC74I+gD9vk7Y8Tvc1o6bhOl+VHZNLZl6pZSU5b5MRFXhuHTHS/9SYiiPburQOuuT41dT2tdue07+XFK/FzKED+GTek/XptZbXmabAXVFQeNxU+5BWPQltKLMFNv5r839ac5ScJu8zhS2OomR9S+2RGn3jViWWQLCXzdvFdogEueNmGmWiRaxHD1TzqsaLBkHK+4G/1C0dKia2X0FrXwqIKHyssX5J65nFKKIVmhCJgHE2GiWJvnGWLqVyaXnAdOafP0ftKOODBAc8geroIGIbHTmQSsMBN0rKuJ5euACFcneU2Z9PIujXBUqYRQYleVOia2RLhGoqUEtC1DvQJDa2hZ1SIHH9FwT9jqX0dygy8A=
  # OC_TOKEN
  - secure: zCOoZ4KiA5ZjY/DB0qWYKiUy5VZc74IRW2SwnE914ShsTvnvKqS4KszJoydS1JtcoMMFkS71Hf0OfmM6+r0qB5f3Yum+X8JXiqcx6EUPfBd5Z+uyzLNNw/YRjUsvg3Yp7DQEQ9YUxij28XPNIXGa86VGW/fr7LiBXr4FLVeUrL+p0CWvUyi64+zjgRN6W82nUkKmR0E5hqQS7dGk26zqM3WnFx6TFZYT7xKSbQQedy6I+W1ZUl0BQipBacevv6WDvK3p+GU/tlYg+bp+l68CLlg7Y29Ar0iGsMrjQozXy7S/DNES1OtU1hBSGov9Gbudfws6KKYZxMbh2oZ6vpEBTZLFQqUxzczVCWQURRoD6rIrRok8SJ5SYb5NKL7S0CcmppR/EH0AuVPDrE2VelkmlKHkF9JO4kJ/q62HV9vVSOV+p/floQPKY8HrRSbyNTSSPeUNNYvcGwb0238hm8tPtB1PKQXbzyqlzhyBi6CB4HfjXuDeNesO7/CUCSIs84rmL83FgSZz5gY29PdILA4x5KQwnC5KwHdQ6OL5ktP6Cd/k4BxOXIH1dnmHy/zqECO5ULlbOyqTYcC5bk8ZLOLW/AdA+KDnfqtNUJv+BBefn+hFWxh4UYRBPcIYdi1LuAS5Hieu/W3PPkL2oqPNFOBUbN54k05dt8N8/XTkhLg5M8k=
services:
- docker
